# Generated by Django 3.1.6 on 2021-06-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('birthday', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tula', models.CharField(max_length=50)),
                ('text', models.TextField(default='')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='post_files')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('RecId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TitikPoetryApp.recruit')),
            ],
        ),
        migrations.CreateModel(
            name='TitikEnterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tshirtcode', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('contact_number', models.IntegerField(null=True)),
                ('RecId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TitikPoetryApp.recruit')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSigya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagebox', models.TextField(default='')),
                ('book_donation', models.ImageField(upload_to=None)),
                ('integer', models.IntegerField(null=True)),
                ('date1', models.DateTimeField(auto_now_add=True)),
                ('RecId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TitikPoetryApp.recruit')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50)),
                ('date2', models.DateTimeField(auto_now_add=True)),
                ('RecId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TitikPoetryApp.recruit')),
                ('publications', models.ManyToManyField(to='TitikPoetryApp.Tula')),
            ],
        ),
    ]
